src/Entity/Punch.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PunchRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PunchRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"content", "id"},
 * message="Cette punch' existe déjà, plagieur que tié"
 * )
 */

class Punch
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $theme;


    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="punches")
     * @ORM\JoinColumn(nullable=true)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="punch", orphanRemoval=true)
     */
    private $comments;

    /**
     * Permet de mettre en place la date de création
     * 
     * @ORM\PrePersist
     *
     * @return void
     */
    public function prePersist(){
        if(empty($this->date)){
            $this->date = new \DateTime();
        }
    }

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }


    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPunch($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPunch() === $this) {
                $comment->setPunch(null);
            }
        }

        return $this;
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour cette punch
     *
     * @return float
     */
    public function getAvgRatings(){
        //Calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0);
        //Faire la division pour avoir la moyenne
        if(count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une punch
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author){

        foreach($this->comments as $comment){
            if($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }

}

src/Form/PunchType.php
<?php

namespace App\Form;

use App\Entity\Punch;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PunchType extends ApplicationType
{


    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('theme', TextType::class, $this->getConfiguration("Thème", "Renseigne le thème narvalo"))
            ->add('content', TextareaType::class, $this->getConfiguration("Punchline", "Partage ton inspi ... fais deuspi"))
            // ->add('author', TextType::class, $this->getConfiguration("Auteur", "Auteur de la punch"))
            // ->add('date', DateType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Punch::class,
        ]);
    }
}

src/Controller/PunchController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Punch;

use App\Entity\Comment;
use App\Form\PunchType;
use App\Form\CommentType;
use App\Repository\PunchRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PunchController extends AbstractController
{
    /**
     * @Route("/punchs", name="punchs_index")
     */
    public function index(PunchRepository $repo): Response{
        $punchs = $repo->findAll();
        
        return $this->render('punch/index.html.twig', [
            'punchs' => $punchs,
        ]);
    }

    /**
     * Créer une punch
     * @Route("/punchs/new", name="punchs_create")
     * @IsGranted("ROLE_USER")
     *
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $manager){
        $punch = new Punch();

        $form = $this->createForm(PunchType::class, $punch);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $punch->setAuthor($this->getUser());

            $manager->persist($punch);
            $manager->flush();

            $this->addFlash(
                'success',
                "La punchline a bien été enregistrée, même si elle est un peu claquée"
            );

            return $this->redirectToRoute('punchs_show', [
                'id' => $punch->getId()
            ]);
        }

        return $this->render('punch/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher le formulaire d'edition
     * 
     * @Route("/punchs/{id}/edit", name="punchs_edit")
     * @Security("is_granted('ROLE_USER') and user === punch.getAuthor()")
     *
     * @return Response
     */
    public function edit(Punch $punch, Request $request, EntityManagerInterface $manager){

        $form = $this->createForm(PunchType::class, $punch);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($punch);
            $manager->flush();

            $this->addFlash(
                'success',
                "Les modifications de la punch' ont bien été enregistrées"
            );

            return $this->redirectToRoute('punchs_show', [
                'id' => $punch->getId()
            ]);
        }

        return $this->render('punch/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/punchs/{id}", name="punchs_show")
     */
    public function show(Punch $punch, Request $request, EntityManagerInterface $manager){

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $comment->setPunch($punch)
                    ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                "Ton commentaire a bien été enregistré"
            );
        }

        return $this->render('punch/show.html.twig', [
            'punch' => $punch,
            'form'  => $form->createView()
        ]);
    }

    /**
     * Supprimer une annonce
     * 
     * @Route("/punchs/{id}/delete", name="punchs_delete")
     * @Security("is_granted('ROLE_USER') and user == punch.getAuthor()")
     *
     * @param Punch $punch
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function delete(Punch $punch, EntityManagerInterface $manager) {
        $manager->remove($punch);
        $manager->flush();

        $this->addFlash(
            'success',
            "La punch a bien été supprimée, et c'est pas du luxe"
        );

        return $this->redirectToRoute("punchs_index");
    }

}

templates/punch/_punch.html.twig
{% block stylesheets %}
        <link rel="stylesheet" href="/css/punch.css">
{% endblock %}

{% set url = path('punchs_show', {'id' : punch.id}) %}

<a href="{{ url }}" style="text-decoration: none;">

    <div class="card disabled col-md-8 p-0 text-center m-2 punch-cards">
        <div class="card-header d-flex text-success px-4 py-1">
            <p class="mb-0">{{punch.theme|capitalize}}</p>
            <p class="ms-auto mb-0">{{punch.author.username|capitalize}}</p>
        </div>
        <div class="card-body p-1">

            <h5 class="card-text p-2 px-4 text-white punch-content">{{punch.content|capitalize}}</h5>
            
        </div>
        <div class="card-footer d-flex px-4 py-1">
            <small class="text-success">{{punch.date|date("d/m/Y")}}</small>

            <div class="mx-auto">
                <a href="{{ url }}" class=" btn btn-secondary m-0 py-0 p-2 text-white bg-success mx-1">Afficher</a>
                {% if app.user and app.user == punch.author %}
                <a href="{{ path('punchs_edit', {'id': punch.id}) }}" class="btn btn-secondary bg-warning m-0 py-0 p-2 mx-1">Modifier</a>
                {% endif %}
            </div>

            {% if punch.comments|length > 0 %}
                <div class="">
                {% include 'partials/rating.html.twig' with {'rating': punch.avgRatings} %}
                </div>
            {% else %}
                <small class="text-warning">Pas encore noté</small>
            {% endif %}


        </div>


    </div>

</a>

templates/punch/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer la punch'{% endblock %}

{% block stylesheets %}
        <link rel="stylesheet" href="/css/punchline_edit.css">
{% endblock %}

{% block body %} 
<div class="row col-12 edit-container justify-content-center">
    <h1 class="text-center my-4">Modifie ta punch'</h1>
<div class="row col-8 my-5 edit_form_container p-5">

    {{ form_start(form) }}

    {{ form_widget(form) }}

    <div class="text-center mb-3 pt-3">
        <button type="submit" class="btn btn-success col-2">Valider</button>
    </div>
    {{ form_end(form) }}

</div>
</div>


{% endblock %} 

templates/punch/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les punch'{% endblock %}
{% block stylesheets %}
        <link rel="stylesheet" href="/css/punchlines_index.css">
{% endblock %}

{% block body %}

<h1 class="text-center text-white mt-2">Liste des punch' des behloul</h1>


<div class="row justify-content-center mx-auto col-8 mb-5">
{% for punch in punchs %}
    {% include 'punch/_punch.html.twig' %}
{% endfor %}
</div>

{% endblock %}

templates/punch/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crée ta punch' narvalo{% endblock %}

{% block stylesheets %}
        <link rel="stylesheet" href="/css/punchline_add.css">
{% endblock %}

{% block body %} 
    <h1 class="text-center mt-5 mb-3">Ajouter une punch' de botch</h1>

<div class="row col-12 create-container justify-content-center">
<div class="col-8 create_form_container my-5 p-5">

    {{ form_start(form) }}

    {{ form_widget(form) }}
    <div class="btn-new-form text-center mb-2 pt-4">
        <button type="submit" class="btn btn-success col-2 ">Valider</button>
    </div>  

    {{ form_end(form) }}

</div>
</div>

{% endblock %} 

templates/punch/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wééé{% endblock %}
{% block stylesheets %}
        <link rel="stylesheet" href="/css/punchline_show.css">
{% endblock %}

{% block body %} 

<div class="punchView row col-12 text-white mt-5 mb-5">
    <div class="row col-3 text-center justify-content-center">
        {% set p = punch.author %}
        <div class="col-8 user-card m-2 text-white">

        <div class="img">
            <a href="{{ path('user_show', {'id': p.id})}}">
                <img src="{{p.picture}}" class="avatar avatar-medium mt-5 mb-2" alt="Avatar de la personne">
            </a>
        </div>
            <a href="{{ path('user_show', {'id': p.id})}}">
                <h3 class="my-3">{{p.username | capitalize}}</h3>
            </a>
            <span class="py-3"> Nombre de punchs: {{p.punches | length}}</span>
            <p class="py-3">Description: {{p.description}}</p>
        </div>
    </div>

    <div class="row col-9 text-center justify-content-center">
        <h1 class="text-white">La punch :</h1>
        <div class="col-10 punch-card m-2 p-3">
            <h4 class="my-3 text-success">{{punch.theme|capitalize}}</h4>
            <p class="punch-content my-3">{{punch.content|capitalize}}</p>
            
            <a href="{{ path('punchs_index') }}" class="btn btn-secondary m-1 p-2 mb-2">Retour</a>

            {% if app.user and app.user == punch.author %}
            <a href="{{ path('punchs_edit', {'id': punch.id}) }}" class="btn btn-warning m-1 p-2 mb-2">Modifier</a>

            <a href="{{ path('punchs_delete', {'id': punch.id}) }}" class="btn btn-danger m-1 p-2 mb-2" onclick="return confirm(`Tu veux vraiment supprimer cette punch bien fatch?`)">Supprimer</a>

            {% endif %}

            <div class="row col-2">
            <small class="">{{punch.date|date("d/m/Y")}}</small>
            </div>
        </div>

        {% if punch.comments|length > 0 %}

            <div class="global-mark col-10 p-4">
              <div class="alert-heading">
              <div class="row col-8 align-items-center">
              <div class="col">
                <h5>Note globale : </h5>
              </div>
              <div class="col">
                {% include 'partials/rating.html.twig' with {'rating': punch.avgRatings} %}
                {# <br> #}
              </div>
            <div class="col">
                <small>(Calculée sur {{punch.comments|length}} punchlinerz)</small>
                </div>
              </div>
              </div>
            </div>

            <h2 class="m-4 text-white">Commentaires des punchlinerz :</h2>
            {% for comment in punch.comments %}
                <div class=" col-10 comment-card mb-3 py-3 px-3">
                    <strong>{{comment.author.username|capitalize}}</strong> :
                    <blockquote class="m-0 p-1">
                        {{comment.content|capitalize}}
                    </blockquote>
                    <strong>Note :</strong>
                    {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                </div>
            {% endfor %}
        {% else %}
            <h2 class="my-5">Cette punch n'a pas encore été commentée mskina...</h2>
        {% endif %}
    {% if is_granted('ROLE_USER') %}
    <div class="mark-card col-10 p-4">
            {% set comment = punch.commentFromAuthor(app.user) %}
            {% if comment is not null %}
            <h2 class="alert-heading text-center">T'as déjà noté cette punch</h2>
                <blockquote>
                    {{comment.content}}
                </blockquote>
                <strong>Note: </strong> {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
            {% else %}

            <h2 class="alert-heading">Note cette punch sans vergogne:</h2>
            {{ form_start(form) }}
            {{ form_widget(form) }}
                <div class="text-center">
                <button type="submit" class="btn btn-success">Valider</button>
                </div>
            {{ form_end(form) }}

            {% endif %}
        {% endif %}
    </div>
    </div>



{% endblock %} 